name: GitHub Actions Demo

on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  merge_group:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: | 
            echo "Job triggered by event ${{ github.event_name }}"
            echo "Branch name is ${{ github.ref }} and repo is ."
            
      - uses: actions/checkout@v3.3.0
      
      - name: List files in repo
        run: tree
